### ISSUE TITLE
tashkeel Marks

### ISSUE THREAD

**Issue by Mahansaa** [alif-type/aref-ruqaa#18] opened 2018-05-16 09:15 UTC
Sometimes Tashkeels overlaps with the letters. could you fix that?
![ruqqa](https://user-images.githubusercontent.com/39330966/40108353-b173d8a4-590b-11e8-9bad-e4f78447e5a5.png)

**Comment by khaledhosny** [comment] 2018-05-16 14:07
I fixed the kaf-lam clash, the tashkil clash is a duplicate of issue #8.

**Closed by khaledhosny** 2018-05-16 14:07 UTC
Labels: bug
